version: "3"

services:
  postgres_db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=appointment
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=SU2orange!
    ports:
      - "5432:5432"
    hostname: postgres_db
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data:
