version: "3"

services:
  postgres_db:
    image: postgres:14.5
    environment:
      - POSTGRES_DB=boki
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=SU2orange!
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  mongo_db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=SU2orange!
      - MONGO_INITDB_DATABASE=boki
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data/db"

volumes:
  postgres-data:
  mongo-data: